### ISSUE TITLE
Bugs and Suggestions

### ISSUE THREAD

**Issue by 0ldi** [nulajedan/Rares#1]
Greetings, good job man.
I tested, and detecting is pretty good.
Rare is released, the sound is played back, all right, in fact I have not found any significant bugs.
- The only probably is that rare's name does not fit in the window, but I think you know about it :)
- Well, the very specific situation where rares are in one place, then the sound is played back 1 time (as I understand it has to repeat delay)
- I would also like to clarify whether there is a filter for excluding Rare Elites within the Molten Core and other (do not want to see and hear each detecting Lava Surger), I can not test it right now, so ask.

Let's move to the Suggestions:
1) I using SilverDragon because marks on the map, and because it supports FuBar. People appreciate their free space on the screen, so FuBar integrating highly recommended, and it is very comfortable.
2) Also it would be nice to have a full map markers database for all Rares (in SilverDragon base is not complete). And the optional disabling in FuBar for all markers.
3) Also it would be perfect if Rare dying in a radius of your vision, it's triggering the countdown to the next repawn and shows it in window near "last time seen" :)

**Comment by nulajedan** [comment]
Hey 0ldi, many thanks for your comments...

- **_rare's name does not fit in the window_**<br/>
I'm well aware of that bug.  I've made quick fix for this issue with new slash command **/rares tb**. This command basically hide or show frame/window background and border. Yes, I know it's not good solution, but I'm still considering how to fix/improve frame/window when rare's name is too long.
- **_filter for excluding Rare Elites within the Molten Core_**<br/>
Addon is checking every _1 sec_ for rare npcs for your zone. I'm pretty sure that Molten Core is not listed, so there's no chance that anything will be detected in this zone. If you mouse over frame/window while in any zone that's not listed in database it will show you message:<br/>**No rare(s) found for zone {YOUR_ZONE}**
- **_FuBar plugin_**<br/>
On TODO list list, high priority. I'm using Fubar, but Titan is also considered.
- **_full map markers database_**<br/>
Well, for that I need coordinates for each rare npc. For now, addon is collecting coordinates when you found rare npc. Coordinate is based on your position where you spotted npc. Be aware that some of the rare npcs is wandering around (not in one place, eg [Ghost Howl](https://vanilla-twinhead.twinstar.cz/?npc=3056)). Not to mention that integration need to be done with default map, Cartographer, Metamap. On TODO list, but very low priority.
- **_countdown to the next repawn_**<br/>
This would be nice, added to TODO list. It needs good research before implementation. Hardest part would be to find respawn timers for each rare npc. I'm not sure how it works in instanced areas (dungeons).

Be aware that I have very limited time with addon development and playing WoW, do not expect to see bugfixes/new features implemented in short time.
I'm happy when I have time to play WoW for more than 1 hour :) (Hardcore casual)

**Comment by 0ldi** [comment]
Thank you for your prompt response. I'm not trying to rush you, just offer ideas for the future if you like it :)
I am very happy about FuBar and filtering.

> 
countdown to the next repawn
This would be nice, added to TODO list. It needs good research before implementation. Hardest part would be to find respawn timers for each rare npc. I'm not sure how it works in instanced areas (dungeons).

I think rares inside dungeons has random chance for each individual generated dungeon, so it is does not make sense to keep track of their respawn, and you can skip.
Another thing, outdoors rares, I think there are some Ranges time of respawn, which assigned all rares. I try to search information but not very successful. Finding information about each specific rare in comments on wowhead too much work, and it may not be accurate. It should be such as to find the source or ask developers like Mangos these data, but I do not know and where to ask :)
The same problem is not fixed respawn, but here you can just use first timer for start respawn and additional timer for end.
Honestly i use addon called Timers, where you can configure any number of timers that are started by triggers (such as the death of someone either). But I'm too lazy to look for all the rares and add them manually :)

> full map markers database
Well, for that I need coordinates for each rare npc. For now, addon is collecting coordinates when you found rare npc. Coordinate is based on your position where you spotted npc. Be aware that some of the rare npcs is wandering around (not in one place, eg Ghost Howl). Not to mention that integration need to be done with default map, Cartographer, Metamap. On TODO list, but very low priority.

In fact, map notes in SilverDragon made pretty well, you can just use them at itself until you do better. There is not as important as the accuracy of marker just his presence. Where Rare have met there and noted it. For example, you run, lazy questing, open the map and nearby marked Rare, well, checks his if it is on the way :)
With regard to the creation of the finished base of Rares, here can help addon ShaguDB, or any web database, and as I mentioned earlier is not so important to indicate the entire route, you can specify one point (preferably the initial spawn.
With best regards

**Comment by nulajedan** [comment]
I'm gonna close this "issue" because fubar plugin and cartographer notes are implemented.
Timers and full map notes needed further investigation before implementation (low priority for now)

**Comment by 0ldi** [comment]
Small suggestions:
1) If you kill \ or just after relog detecting same Rare, the worldmap becomes littered. Yes, you can manually delete the points, but it may be better to make the limit of 1 point (if possible).
2) When recording "Last seen" written subzone of main zone, but ... its less convenient than coordinates, may be recorded both? :)
3) And you can use the color style like:
-not seen all gray
-lvl = gray if >10 of your's lvl, green >3<10, yellow if -+3, etc orange, red
-all rares names: a certain color
-dates: a certain color
-times: a certain color
-subzones: a certain color
-coordinates: a certain color
4) Also it is possible to reduce:
- "Seen 1 time (s)" to "seen (1)"
- "last time on" to "last:"
None of pressure, just offer :)

**Comment by nulajedan** [comment]
> 1) If you kill \ or just after relog detecting same Rare, the worldmap becomes littered. Yes, you can manually delete the points, but it may be better to make the limit of 1 point (if possible).

I'm still researching how to limit that to only 1 map marker per rare.

> 2) When recording "Last seen" written subzone of main zone, but ... its less convenient than coordinates, may be recorded both? :)

Recording both coordinates and subzone (if subzone exists). This will be, with all other collected and known info, shown in Rares Browser (scheduled for release 0.9.0, not before).

> 3) And you can use the color style like ...
4) Also it is possible to reduce ...

Of course :)  I'll se what I can do in future releases ...

**Comment by 0ldi** [comment]
3D models look pretty cute, but I reduced the size of 2 times (for myself) to find a place for them. 
Is it possible to make this 3D area ignored the click of a mouse?

**Comment by 0ldi** [comment]
Foobar tooltip missing (when I direct the mouse cursor on Rares nothing happens, there is no list)

**Comment by nulajedan** [comment]
I'm not sure if you have latest version [v0.6.2](https://github.com/nulajedan/Rares/releases/tag/v0.6.2) ... 
There was a bug with Fubar tooltip which was fixed with this version (issue: [Issue #6](https://github.com/nulajedan/Rares/issues/6))

**Comment by 0ldi** [comment]
i always use latest version before report, rares list work only when i mouseover on the radar (circle), when i try it in FuBar or left mouse-click - nothing happen. Only right-click work (options)

**Comment by nulajedan** [comment]
You're correct! My apologies because I'm not using Fubar and thought it was fixed with latest version.
Please dl latest release [v0.6.3](https://github.com/nulajedan/Rares/releases/tag/v0.6.3)
